#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

source ProdConfig
BASEDIR="$WORKSPACE_ROOT/sitechat"
CLASSPATH=$BASEDIR/classes:`find $BASEDIR/lib -type f -name '*.jar' | sed 's/^/*/' | xargs | sed 's/ \*/:/g' | sed 's/^*//'`
CLASSNAME=`echo $1 | sed 's/^.*\.\(.*\)$/\1/'`

echo java -Xms256m -Xmx512m -cp $CLASSPATH net.mafiascum.web.sitechat.server.SiteChatServer --verbose -p 4241 -d file:$BASEDIR &>> $BASEDIR/server.out

#java -Xms256m -Xmx512m -cp $CLASSPATH net.mafiascum.web.sitechat.server.SiteChatServer --verbose -p 4241 -d file:$BASEDIR &
java -Xms1024m -Xmx2048m -cp $CLASSPATH net.mafiascum.web.sitechat.server.SiteChatServer --verbose -p 4241 -d file:$BASEDIR &>> $BASEDIR/server.out &
