#!/bin/bash

IsProcessRunning() {

#	RUNNING_PROCESSES=`ps | grep $1 | grep -v grep`
	RUNNING_PROCESSES=`ps axuw | grep $1 | grep -v grep`

	if [[ "$RUNNING_PROCESSES" == *"$1"* ]];
	then
		PROCESS_IS_RUNNING=true
	else
		PROCESS_IS_RUNNING=false
	fi
}

PROCESS_IS_RUNNING=false
#PID=`sockstat -4 -l | grep :4241 | awk '{print $3}' | head -1`
PID=`netstat -nlp | grep ":4241" | awk '{print $7;}' | sed -E 's/\/.*//g'`

if [ -z "$PID" ];
then
	echo "No Process Found For Server..."
	exit
fi

echo "Server Process ID: $PID"

IsProcessRunning $PID

if $PROCESS_IS_RUNNING;
then

	echo -ne "Attempting nice kill"
	kill $PID

	COUNTER=0
	while [ $COUNTER -lt 15 ]
	do
		sleep 1
		IsProcessRunning $PID

		COUNTER=$(($COUNTER+1))
		echo -ne "...$COUNTER"

		if ! $PROCESS_IS_RUNNING ;
		then
			break
		fi
	done
else
	echo "Server is not running."
	exit
fi


echo ""
IsProcessRunning $PID


if $PROCESS_IS_RUNNING;
then

	echo -ne "Attempting hard kill"
	kill -9 $PID

	COUNTER=0
	while [ $COUNTER -lt 15 ]
	do
		sleep 1
		IsProcessRunning $PID

		COUNTER=$(($COUNTER+1))
		echo -ne "...$COUNTER"

		if ! $PROCESS_IS_RUNNING ;
		then
			break
		fi
	done
fi

echo ""
IsProcessRunning $PID

if ! $PROCESS_IS_RUNNING;
then
	echo "Server is no longer running."
else
	echo "Server is still running."
fi

